apiVersion: app/v1
kind: Deployment
metadata:
  name: java-aws-deployment
spec:
  selector:
    matchLabels: java-aws-k8s
  replicas: 2
  template: # Configuration of the pod
    metadata:
      labels:
        app: java-aws-k8s
    spec:
      containers:
        - name: java-aws-k8s
          image: 1190514/javajenkinsaws
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the clu

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: java-aws-service
spec:
  selector:
    app: java-aws-k8s # Should match the label of the pod
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service. Should match the container port
  type: NodePort # type of the service.